{{- $env := .Values.env -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: application-props
binaryData:
{{ $path := "$env/application.properties" }}
{{ $name := base $path }}
{{- printf "%s" $name}}{{ print ": "}}{{ $.Files.Get $path | b64enc }}
