apiVersion: v1
data:
  ENV_NAME: {{ .Values.env | quote }}
  {{- range $key, $val := .Values.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
kind: ConfigMap
metadata:
  name: pma-api-config
