{{- $env := .Values.env -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: application-props
data:
  application.properties: |-
    {{ .Files.Get "./pma-api/$env/application.properties" | nindent 4 }}
