apiVersion: v1
data:
  TESCO_API_BASE_URL: {{ .Values.TESCO_API_BASE_URL }}
  ONE_LOGIN_BASE_URL: {{ .Values.ONE_LOGIN_BASE_URL }}
  AD_ROLE_ADMIN: {{ .Values.AD_ROLE_ADMIN }}
  AD_ROLE_LINE_MANAGER: {{ .Values.AD_ROLE_LINE_MANAGER }}
  IDENTITY_CLIENT_ID: {{ .Values.IDENTITY_CLIENT_ID | quote }}
  PMA_DB_URL: {{ .Values.PMA_DB_URL }}
  PMA_DB_SCHEMA: {{ .Values.PMA_DB_SCHEMA }}
  PMA_DB_USERNAME: {{ .Values.PMA_DB_USERNAME }}
kind: ConfigMap
metadata:
  name: pma-api-config
