apiVersion: v1
kind: Secret
metadata:
  name: pma-api-secrets
type: Opaque
data:
  IDENTITY_CLIENT_SECRET: {{ .Values.IDENTITY_CLIENT_SECRET | b64enc | quote }}
  PMA_DB_PASSWORD: {{ .Values.PMA_DB_PASSWORD | b64enc | quote }}
