apiVersion: v1
kind: Service
metadata:
  name: {{ include "pma-api.fullname" . }}
  labels:
    {{- include "pma-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.serviceIdentity.port }}
      targetPort: http-identity
      protocol: TCP
      name: http-identity
    {{- if .Values.serviceManagement.enabled }}
    - port: {{ .Values.serviceManagement.port }}
      targetPort: http-management
      protocol: TCP
      name: http-management
    {{- end }}
  selector:
    {{- include "pma-api.selectorLabels" . | nindent 4 }}
