package com.tesco.pma.error;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.tesco.pma.api.CodeAware;
import com.tesco.pma.api.TargetAware;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.experimental.SuperBuilder;

import java.util.ArrayList;
import java.util.List;

/**
 * Main app ApiError, generated by {@link ApiExceptionHandler}
 */
@Getter
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class ApiError extends ErrorDetail implements CodeAware, TargetAware {
    private String target;

    private final List<ErrorDetail> details = new ArrayList<>();

    public void addDetails(ErrorDetail errorDetail) {
        details.add(errorDetail);
    }



}
