package com.tesco.pma.event;

public enum EventNames {
    PM_COLLEAGUE_CYCLE_ASSIGNMENT,
    POST_IMPORT_NEW_COLLEAGUE,
    POST_CEP_COLLEAGUE_ADDED,
    CEP_COLLEAGUE_UPDATED,
    CEP_COLLEAGUE_LEFT
}
