spring:
  application:
    #name: pma-api
    index: ${random.uuid}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${TESCO_API_BASE_URL}/identity/v4/issue-token
          jwk-set-uri: ${TESCO_API_BASE_URL}/.well-known/jwks.json
        opaquetoken:
          client-id: ${IDENTITY_CLIENT_ID}
          client-secret: ${IDENTITY_CLIENT_SECRET}
          introspection-uri: ${TESCO_API_BASE_URL}/identity/v4/issue-token/introspect
      client:
        registration:
          identity:
            client-id: ${IDENTITY_CLIENT_ID}
            client-secret: ${IDENTITY_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            client-authentication-method: POST
            scope:
              - internal
              - public
            provider: identity
        provider:
          identity:
            token-uri: ${TESCO_API_BASE_URL}/identity/v4/issue-token/token
  mvc:
    format:
      date-time: iso
      date: iso
      time: iso
  datasource:
    default:
      # Database config
      driver-class-name: org.postgresql.Driver
      jdbc-url: ${PMA_DB_URL}
      schema: ${PMA_DB_SCHEMA}
      username: ${PMA_DB_USERNAME}
      password: ${PMA_DB_PASSWORD}
      type: com.zaxxer.hikari.HikariDataSource
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 10
      #idle-timeout: 60000
      #max-life-time: 1750000
      pool-name: default_ds_pool
      is-auto-commit: false
      # MyBatis config
      mybatis-session:
        type-aliases-package: com.tesco.pma.api,
                              com.tesco.pma.colleague.profile.domain,
                              com.tesco.pma.organisation.api,
                              com.tesco.pma.review.domain,
                              com.tesco.pma.process.api,
                              com.tesco.pma.cycle.api,
                              com.tesco.pma.feedback.api,
                              com.tesco.pma.colleague.security.domain,
                              com.tesco.pma.notes.model,
                              com.tesco.pma.fs.domain,
                              com.tesco.pma.config.domain,
                              com.tesco.pma.tip.api,
                              com.tesco.pma.pdp.api,
                              com.tesco.pma.pdp.domain,
                              com.tesco.pma.reporting.review.domain,
                              com.tesco.pma.reporting.dashboard.domain
        configuration-properties:
          base-package: com.tesco.pma.dao,
                        com.tesco.pma.colleague.profile.dao,
                        com.tesco.pma.organisation.dao,
                        com.tesco.pma.review.dao,
                        com.tesco.pma.process.dao,
                        com.tesco.pma.cycle.dao,
                        com.tesco.pma.feedback.dao,
                        com.tesco.pma.colleague.security.dao,
                        com.tesco.pma.notes.dao,
                        com.tesco.pma.fs.dao,
                        com.tesco.pma.config.dao,
                        com.tesco.pma.tip.dao,
                        com.tesco.pma.pdp.dao,
                        com.tesco.pma.reporting.dashboard.dao,
                        com.tesco.pma.reporting.review.dao
          batchSize: 500
    camunda:
      # Camunda database config
      driver-class-name: org.postgresql.Driver
      jdbc-url: ${PMA_DB_URL}
      schema: ${CAMUNDA_DB_SCHEMA}
      username: ${PMA_DB_USERNAME}
      password: ${PMA_DB_PASSWORD}
      type: com.zaxxer.hikari.HikariDataSource
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 10
      pool-name: camunda_ds_pool
      is-auto-commit: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 128MB
      max-request-size: 128MB
  messages:
    basename: >
      com/tesco/pma/exception/AppExceptionMessage,
      com/tesco/pma/colleague/profile/exception/AppExceptionMessage,
      com/tesco/pma/organisation/service/AppConfigEntryMessages,
      com/tesco/pma/review/exception/AppExceptionMessage,
      com/tesco/pma/feedback/exception/AppExceptionMessage,
      com/tesco/pma/cycle/exception/AppExceptionMessage,
      com/tesco/pma/process/service/AppPMProcessMessages,
      com/tesco/pma/config/import/AppImportMessages,
      com/tesco/pma/colleague/security/exception/AppExceptionMessage,
      com/tesco/pma/notes/exception/AppNotesMessages,
      com/tesco/pma/fs/exception/AppExceptionMessage,
      com/tesco/pma/flow/BPMExceptionMessages,
      com/tesco/pma/tip/exception/AppExceptionMessage,
      com/tesco/pma/event/exception/AppEventMessage,
      com/tesco/pma/pdp/exception/AppExceptionMessage,
      com/tesco/pma/reporting/dashboard/exception/AppExceptionMessage
    encoding: UTF-8
  async-executor:
    core-pool-size: 2
    max-pool-size: 5
    queue-capacity: 10
server:
  port: 8083
  servlet:
    context-path: /v1
  trusted-port: 8084
  trusted-path-prefix: /v1/user-management
#  forward-headers-strategy: NATIVE
management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
      probes:
        enabled: true
    shutdown:
      enabled: true
springdoc:
  version: ${PMA_PROJECT_VERSION}
  show-actuator: true
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
validation:
  mapping-locations:
    - classpath:com/tesco/pma/feedback/validation/constraints-feedback.xml
    - classpath:com/tesco/pma/tip/validation/constraints-tip.xml
    - classpath:com/tesco/pma/validation/constraints-files-upload-metadata.xml
    - classpath:com/tesco/pma/validation/constraints-upload-metadata.xml
    - classpath:com/tesco/pma/validation/constraints-pdp-goal.xml
  messages:
    basename: com/tesco/pma/validation/AppValidationMessages
    encoding: UTF-8
tesco:
  application:
    name: pma
    security:
      enabled: ${SECURITY_ENABLED:true}
      additional-auth:
        enabled: true
        token-header-name: Authorization-App
        jwt: # TODO Onelogin should return all these URL via config endpoint
          issuer-uri: ${ONE_LOGIN_BASE_URL}/oidc/2
          jwk-set-uri: ${ONE_LOGIN_BASE_URL}/oidc/2/certs
      role-mapping:
        ROLE_Admin: ${AD_ROLE_ADMIN}
        ROLE_Colleague: ${AD_ROLE_COLLEAGUE}
        ROLE_LineManager: ${AD_ROLE_LINE_MANAGER}
        ROLE_PeopleTeam:  ${AD_ROLE_PEOPLE_TEAM}
        ROLE_TalentAdmin: ${AD_ROLE_TALENT_ADMIN}
        ROLE_ProcessManager: ${AD_ROLE_PROCESS_MANAGER}
        ROLE_Executive: ${AD_ROLE_EXECUTIVE}
      default-user:
        uuid: ${DEFAULT_USER_UUID:10000000-1000-1000-1000-100000000001}
    rest-template:
      security:
        enabled: ${REST_TEMPLATE_SECURITY_ENABLED:true}
      connect-timeout: 20000
      read-timeout: 30000
    page:
      size: 20
    healthcheck:
      indicators:
        -
          name: defaultPostgreSQLDB
          description: Default database
          url: ${spring.datasource.default.jdbc-url}
          beanName: databaseHealthIndicator
          reference: defaultDataSource
          validationQuery: "SHOW server_version"
        -
          name: identityAPI
          url: ${TESCO_API_BASE_URL}/identity/_status
          description: Identity API
          beanName: restHealthIndicator
        -
          name: colleagueFactsAPI
          url: ${TESCO_API_BASE_URL}/colleague/_status
          description: Colleague Facts API
          beanName: restHealthIndicator
    external-endpoints:
      cep:
        subject: ${CEP_SUBJECT}
        publish:
          url: ${TESCO_API_BASE_URL}/colleague/v1/events
        retry-timeout: 30
        subscribe:
          feeds:
            jit: colleagues-jit-v1
            immediate: colleagues-immediate-v1
      colleague-api:
        base-url: ${TESCO_API_BASE_URL}/colleague/v2/colleagues
      events-api:
        base-url: ${PMA_API_URL}/events
      contact-api:
        messaging-url: ${TESCO_API_BASE_URL}/messaging/v1/send
      colleague-inbox-api:
        base-url: ${TESCO_API_BASE_URL}/colleague/v1/inbox/messages
    event-mapping:
      # Review notifications events
      PM_REVIEW_BEFORE_START: com.tesco.pma.bpm.action.RunFlowByEventAction
      PM_REVIEW_SUBMITTED: com.tesco.pma.bpm.action.RunFlowByEventAction
      PM_REVIEW_APPROVED: com.tesco.pma.bpm.action.RunFlowByEventAction
      PM_REVIEW_DECLINED: com.tesco.pma.bpm.action.RunFlowByEventAction
      PM_REVIEW_BEFORE_END: com.tesco.pma.bpm.action.RunFlowByEventAction
      # Import events
      PM_COLLEAGUE_CYCLE_ASSIGNMENT: com.tesco.pma.bpm.action.RunFlowByEventAction
      POST_IMPORT_NEW_COLLEAGUE: com.tesco.pma.colleague.security.action.CreateAccountByEventAction
      # CEP events
      POST_CEP_COLLEAGUE_ADDED: com.tesco.pma.colleague.security.action.CreateAccountByEventAction
      CEP_COLLEAGUE_UPDATED: com.tesco.pma.bpm.action.RunFlowByEventAction
      CEP_COLLEAGUE_LEFT: com.tesco.pma.bpm.action.RunFlowByEventAction
      # TIPS events
      NF_TIPS_RECEIVED: com.tesco.pma.bpm.action.RunFlowByEventAction
      # Feedbacks events
      NF_FEEDBACK_GIVEN: com.tesco.pma.bpm.action.RunFlowByEventAction
      NF_FEEDBACK_REQUESTS_RESPONDED: com.tesco.pma.bpm.action.RunFlowByEventAction
      NF_FEEDBACK_REQUESTED: com.tesco.pma.bpm.action.RunFlowByEventAction
      # Objectives
      NF_ORGANISATION_OBJECTIVES: com.tesco.pma.bpm.action.RunFlowByEventAction
      NF_OBJECTIVES_APPROVED_FOR_SHARING: com.tesco.pma.bpm.action.RunFlowByEventAction
      NF_OBJECTIVE_SHARING_START: com.tesco.pma.bpm.action.RunFlowByEventAction
      NF_OBJECTIVE_SHARING_END: com.tesco.pma.bpm.action.RunFlowByEventAction
      # Review
      NF_PM_REVIEW_SUBMITTED: com.tesco.pma.bpm.action.RunFlowByEventAction
      NF_PM_REVIEW_APPROVED: com.tesco.pma.bpm.action.RunFlowByEventAction
      NF_PM_REVIEW_DECLINED: com.tesco.pma.bpm.action.RunFlowByEventAction
      NF_PM_REVIEW_BEFORE_START: com.tesco.pma.bpm.action.RunFlowByEventAction
      NF_PM_REVIEW_BEFORE_END: com.tesco.pma.bpm.action.RunFlowByEventAction
      NF_PM_REVIEW_START: com.tesco.pma.bpm.action.RunFlowByEventAction
      NF_PM_REVIEW_END: com.tesco.pma.bpm.action.RunFlowByEventAction
    user-management:
      page:
        size: 100
      subject: ${IAM_INTEGRATION_SUBJECT}
    pdp:
      template:
        key: pdp/templates/Personal Development Plan Template.pptx
      form:
        key: pdp/forms/standard_pdp.form

camunda:
  bpm:
    database:
      schema-update: false
    metrics:
      enabled: true
    #      db-reporter-activate: true
    job-execution:
      enabled: false
    id-generator: strong
#    deployment-resource-pattern: classpath:*.bpmn
#   todo: remove in production
    auto-deployment-enabled: true
    deployment-resource-pattern: classpath:com/tesco/pma/flow/standard_init_timeline_point.bpmn,
                                           com/tesco/pma/flow/notifications/review/review_flow.bpmn,
                                           com/tesco/pma/flow/notifications/review/review_notifications_decisions.dmn,
                                           com/tesco/pma/flow/notifications/review/review_event_to_attribute.dmn,
                                           com/tesco/pma/flow/notifications/review/review_event_to_template_id.dmn,
                                           com/tesco/pma/flow/notifications/review/review_event_to_content.dmn,
                                           com/tesco/pma/flow/notifications/review/review_event_to_title.dmn,
                                           com/tesco/pma/flow/notifications/objectives/objectives_flow.bpmn,
                                           com/tesco/pma/flow/notifications/objectives/objectives_event_to_attribute.dmn,
                                           com/tesco/pma/flow/notifications/objectives/objectives_notification_decisions.dmn,
                                           com/tesco/pma/flow/notifications/objectives/objectives_event_to_template_id.dmn,
                                           com/tesco/pma/flow/notifications/objectives/objectives_event_to_content.dmn,
                                           com/tesco/pma/flow/notifications/objectives/objectives_event_to_title.dmn,
                                           com/tesco/pma/flow/notifications/feedback/feedback_flow.bpmn,
                                           com/tesco/pma/flow/notifications/feedback/feedback_event_to_attribute.dmn,
                                           com/tesco/pma/flow/notifications/feedback/feedback_notification_decisions.dmn,
                                           com/tesco/pma/flow/notifications/feedback/feedback_event_to_template_id.dmn,
                                           com/tesco/pma/flow/notifications/feedback/feedback_event_to_content.dmn,
                                           com/tesco/pma/flow/notifications/cycle/cycle_flow.bpmn,
                                           com/tesco/pma/flow/notifications/cycle/cycle_event_to_attribute.dmn,
                                           com/tesco/pma/flow/notifications/cycle/cycle_notification_decisions.dmn,
                                           com/tesco/pma/flow/notifications/cycle/cycle_event_to_template_id.dmn,
                                           com/tesco/pma/flow/notifications/cycle/cycle_event_to_content.dmn,
                                           com/tesco/pma/flow/notifications/tips/tips_event_to_attribute.dmn,
                                           com/tesco/pma/flow/notifications/tips/tips_flow.bpmn,
                                           com/tesco/pma/flow/notifications/tips/tips_notification_decisions.dmn,
                                           com/tesco/pma/flow/notifications/tips/tips_event_to_template_id.dmn,
                                           com/tesco/pma/flow/reporting/rating/overall_rating.dmn
    deployment-resource-paths: com/tesco/pma/flow

---
spring:
  config:
    activate:
      on-profile: cep-local
tesco:
  application:
    external-endpoints:
      cep:
        publish:
          url: http://localhost:8083/v1/requests/events/local
