spring:
  application:
    #name: pma-api
    index: ${random.uuid}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${TESCO_API_BASE_URL}/identity/v4/issue-token
          jwk-set-uri: ${TESCO_API_BASE_URL}/.well-known/jwks.json
        opaquetoken:
          client-id: ${IDENTITY_CLIENT_ID}
          client-secret: ${IDENTITY_CLIENT_SECRET}
          introspection-uri: ${TESCO_API_BASE_URL}/identity/v4/issue-token/introspect
      client:
        registration:
          identity:
            client-id: ${IDENTITY_CLIENT_ID}
            client-secret: ${IDENTITY_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            client-authentication-method: POST
            scope:
              - internal
              - public
            provider: identity
        provider:
          identity:
            token-uri: ${TESCO_API_BASE_URL}/identity/v4/issue-token/token
  mvc:
    format:
      date-time: iso
      date: iso
      time: iso
  datasource:
    default:
      # Database config
      driver-class-name: org.postgresql.Driver
      jdbc-url: ${PMA_DB_URL}
      schema: ${PMA_DB_SCHEMA}
      username: ${PMA_DB_USERNAME}
      password: ${PMA_DB_PASSWORD}
      type: com.zaxxer.hikari.HikariDataSource
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 10
      #idle-timeout: 60000
      #max-life-time: 1750000
      pool-name: default_ds_pool
      is-auto-commit: false
      # MyBatis config
      mybatis-session:
        type-aliases-package: com.tesco.pma.api, com.tesco.pma.colleague.profile.domain, com.tesco.pma.organisation.api
        configuration-properties:
          base-package: com.tesco.pma.dao, com.tesco.pma.colleague.profile.dao, com.tesco.pma.organisation.dao
          batchSize: 500
    camunda:
      # TODO: change database
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:camunda;MODE=Oracle;DB_CLOSE_DELAY=-1
      #jdbc-url: jdbc:h2:tcp://localhost//opt/h2/db/demo;MODE=Oracle;DB_CLOSE_DELAY=-1
      username: sa
      password:
      type: com.zaxxer.hikari.HikariDataSource
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 10
      maximum-pool-size: 10
      pool-name: camunda_ds_pool
      is-auto-commit: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 128MB
      max-request-size: 128MB
  messages:
    basename: >
      com/tesco/pma/exception/AppExceptionMessage,
      com/tesco/pma/colleague/profile/exception/AppExceptionMessage
    encoding: UTF-8
  async-executor:
    core-pool-size: 2
    max-pool-size: 5
    queue-capacity: 10
server:
  port: 8083
  servlet:
    context-path: /v1
management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
      probes:
        enabled: true
    shutdown:
      enabled: true
springdoc:
  version: ${PMA_PROJECT_VERSION}
  show-actuator: true
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
validation:
  mapping-locations:
    - classpath:com/tesco/pma/validation/constraints-subsidiary.xml
    - classpath:com/tesco/pma/validation/subsidiary-permission.xml
  messages:
    basename: com/tesco/pma/validation/AppValidationMessages
    encoding: UTF-8
tesco:
  application:
    name: pma
    security:
      enabled: ${SECURITY_ENABLED:true}
      additional-auth:
        enabled: true
        token-header-name: Authorization-App
        jwt: # TODO Onelogin should return all these URL via config endpoint
          issuer-uri: ${ONE_LOGIN_BASE_URL}/oidc/2
          jwk-set-uri: ${ONE_LOGIN_BASE_URL}/oidc/2/certs
      role-mapping:
        ROLE_Admin: ${AD_ROLE_ADMIN}
        ROLE_LineManager: ${AD_ROLE_LINE_MANAGER}
        ROLE_Viewer: ${AD_ROLE_VIEWER}
    rest-template:
      security:
        enabled: ${REST_TEMPLATE_SECURITY_ENABLED:true}
      connect-timeout: 20000
      read-timeout: 30000
    page:
      size: 20
    healthcheck:
      indicators:
        -
          name: defaultPostgreSQLDB
          description: Default database
          url: ${spring.datasource.default.jdbc-url}
          beanName: databaseHealthIndicator
          reference: defaultDataSource
          validationQuery: "SHOW server_version"
        -
          name: identityAPI
          url: ${TESCO_API_BASE_URL}/identity/_status
          description: Identity API
          beanName: restHealthIndicator
        -
          name: colleagueFactsAPI
          url: ${TESCO_API_BASE_URL}/colleague/_status
          description: Colleague Facts API
          beanName: restHealthIndicator
    external-endpoints:
      cep:
        subject: ${CEP_SUBJECT}
        publish:
          url: ${TESCO_API_BASE_URL}/colleague/v1/events
        retry-timeout: 30
        subscribe:
          feeds:
            jit: colleagues-jit-v1
            immediate: colleagues-immediate-v1
      colleague-api:
        base-url: ${TESCO_API_BASE_URL}/colleague/v2/colleagues
    event-mapping:
      # TODO add real events
      # sample events
      E_START_1: com.tesco.pma.bpm.action.RunFlowByEventAction
      E_START_2: com.tesco.pma.bpm.action.RunFlowByEventAction

camunda:
  bpm:
    database:
      schema-update: true
    metrics:
      enabled: true
    #      db-reporter-activate: true
    job-execution:
      enabled: false
    id-generator: strong
#    deployment-resource-pattern: classpath:*.bpmn

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    default:
      # Database config
      jdbc-url: ${PMA_DB_URL}
      schema: ${PMA_DB_SCHEMA}
      username: ${PMA_DB_USERNAME}
      password: ${PMA_DB_PASSWORD}

---
spring:
  config:
    activate:
      on-profile: cep-local
tesco:
  application:
    external-endpoints:
      cep:
        publish:
          url: http://localhost:8083/v1/requests/events/local
